### ISSUE TITLE
Move to trash failed - rva-test.appspot.com

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#250] opened 2015-01-26 21:05 UTC
http://www.screencast.com/t/b18BYeVsL

When moving items to trash on company ID fa118ca4-07af-4425-a908-c01e066146ff I get the error "Move to trash failed". When restoring items from trash, nothing restores. This was encountered while QAing tagging on iOS.

FYI @alanclayton

**Comment by alanclayton** [comment] 2015-01-26 21:08
@btfrise I assume this is only occurring on the Test server. Can you confirm? @EnlightenedCode would the cause of this issue be related to tagging?

**Comment by EnlightenedCode** [comment] 2015-01-26 21:47
@alanclayton @btfrise I'll check that company Id....but I am unable to recreate this. I don't think it has anything to do with tagging.  next time go to the Network tab and get a screenshot of the request.

**Comment by EnlightenedCode** [comment] 2015-01-26 21:50
@btfrise can you make a screencast showing this happens repeatably? is it just random?  I am able to delete and restore tagged files fine in my company-id

**Comment by btfrise** [comment] 2015-01-26 21:54
From @fjvallarino:

It seems in the past buckets for both test and production were created on the same instance (the information to decide which one belonged to each environment was somewhere else). Recently they were split into separate projects (one prod, one test), and the credentials are different, so when you try to do that operation it fails.

FYI @alanclayton @EnlightenedCode

**Comment by EnlightenedCode** [comment] 2015-01-26 21:56
@btfrise yes that is correct.  You have to delete your company-id bucket and create a new bucket on test.  This does not affect production so this is not a bug.  @alanclayton do you understand francisco's response? I'll leave it to you to close it.

**Comment by alanclayton** [comment] 2015-01-26 22:01
@EnlightenedCode Is there a chance of this happening to a users bucket on production?

**Comment by EnlightenedCode** [comment] 2015-01-26 23:36
@alanclayton no there is no chance.   this was only affecting our test environments.

**Closed** 2015-01-27 00:36 UTC
Labels: bug
