### ISSUE TITLE
While uploading multiple files, not able to remove the files unless they are on the progress bar

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/storage-client#413] opened 2016-03-25 17:52 UTC
**How to recreate**
1. Go to storage-stage-0.risevision.com
2. Create a new folder 
3. Upload a group of files
3. Select 'Remove' for certain files

**What happens**
In the recording at http://recordit.co/D5Dd9PYoHu, I was able to remove the STScl4.jpg file from being uploaded but only when the progress bar is on it.  I was not able to remove other files when selecting the Remove link.

**What should happen**
When a user is selecting the Remove link for file/s during a batch upload, they should be able to remove that specific file regardless as to whether or not the file is on the progress bar.

**Notes**
Chr 49.0.2623.87
Also appears when uploading multiple files to the Presentation or Placeholder background in https://apps-stage-0.risevision.com/ and http://storage.risevision.com

**Comment by hcs0** [comment] 2016-03-25 18:22
Added in the notes: Also appears when uploading multiple files to the Presentation or Placeholder background in https://apps-stage-0.risevision.com/

**Comment by hcs0** [comment] 2016-03-28 14:04
Occurs on production storage

**Comment by ezequielc** [comment] 2016-03-28 21:15
Duplicate of https://github.com/Rise-Vision/storage-client/issues/401

**Closed by ezequielc** 2016-03-28 21:15 UTC
