### ISSUE TITLE
Sorting by Type column does not sort correcty for files with no extension

### ISSUE THREAD

**Issue by EnlightenedCode** [Rise-Vision/storage-client#249] opened 2015-01-26 21:04 UTC
In order to reproduce this bug you need to upload 2 files that have no file extensions.  
name the first file starting with an "a".
name the second file starting with a "t".
you need to also have other folders and files in your bucket as well.
Upload these two files.  
Click on the Type column to sort. 
Notice that the sorting does not sort the two files with no extension together.

see screencast: http://www.screencast.com/t/PRU0tgasBo4

**Comment by fjvallarino** [comment] 2015-03-19 21:03
Cannot reproduce the issue. Closing it.

**Closed by fjvallarino** 2015-03-19 21:03 UTC
Labels: bug
