### ISSUE TITLE
Store window is not showing entirely when clicking on subscribe from Storage

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/storage-client#368] opened 2015-06-01 17:33 UTC
See here https://db.tt/q5yPF4nf. This is only happening in Storage from what I can see. If I go to Editor or the Support app I see the Store window normally.

@tejohnso @fjvallarino Please let me know who can take this and I'd like to treat it as escalated as its preventing people from purchasing. And can you let us know what caused this?

@robb-price FYI, can you take it from here?

**Comment by fjvallarino** [comment] 2015-06-01 17:35
@brianloosbrock I'll take it.

**Comment by robb-price** [comment] 2015-06-01 17:45
@brianloosbrock Sure. @fjvallarino Let me know when/where it is ready to test, and I can test it out.

Thanks!

**Comment by brianloosbrock** [comment] 2015-06-01 20:58
@fjvallarino Can I get an update on this? Thanks

**Comment by fjvallarino** [comment] 2015-06-01 21:04
@brianloosbrock @robb-price The issue is fixed on https://storage-stage-rva-test.risevision.com (Storage app). You can also check on http://rva-test.appspot.com for In app selector.

The issue seems to be related to a CSS minification bug on common-style's build process. I updated the minification plugin and now everything seems correct. Sorry I took so long to answer, but I'm puzzled as to why we did not have CSS issues earlier and wanted to be sure (on Storage or any other application).

@tejohnso @ghislaineguerin @RV-Adrian FYI

**Comment by robb-price** [comment] 2015-06-01 21:12
Tested at https://storage-stage-rva-test.risevision.com/ and http://rva-test.appspot.com, everything looks as expected. @fjvallarino Let's deploy this first thing in the AM tomorrow if that works for you.

Thanks!

**Comment by robb-price** [comment] 2015-06-02 13:45
Verified in production and closed.

**Closed by robb-price** 2015-06-02 13:45 UTC
Labels: bug
